### PR TITLE
Fix typo in k8s appliances README

### PR DESCRIPTION
**Pull request by fawadkhaliq**
Last section of the k8s appliance README is about worker nodes.
Fixed the typo master->worker to adjust as it should be

### CODE REVIEW

**Comment by AlainRoy** [comment]
Thanks so much for your patch!

Unfortunately, we use an internal tool to manage code reviews and commits, so I can't directly merge this. In addition, we make all changes to our "develop" branch, and automatically merge to the master branch once tests have passed. 

I've started this process, and it will be merged to the develop branch soon. I'll close this request, but your change will be included.

Thanks again!!

**Comment by fawadkhaliq** [comment]
@AlainRoy thanks for explaining and incorporating the patch. 

I have recently started looking at the Photon community and am really interested in contributing to it. Given that reviews and commits are managed using an internal tool, I am wondering what would be the process to propose any changes for someone external like myself. If you could please help explain the process, that would be great.

Thank you!

**Comment by AlainRoy** [comment]
Committed: https://github.com/vmware/photon-controller/commit/9d57505bbe520a91046609bdd28807351466be04

**Comment by AlainRoy** [comment]
We'd love to have you contribute! Let me talk it over with the team and see what we can do. We have a lot on our plate now, but I would be very happy if we could take contributions more easily. Feel free to contact me by email to talk about it further.

**Comment by fawadkhaliq** [comment]
@AlainRoy that sounds great. Thank you.
Absolutely, that would be great. You email address does not seem to be public on your GitHub profile. Can you please share it here or email me at fawadkq@gmail.com, whatever works better. Thanks!

**Pull request closed without merging**
